name: Build and Push Docker Image to Azure

on:
  push:
    branches:
      - main  # or whatever your main branch is

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name azurewebscraper

    - name: Build and Push Docker Image
      run: |
        docker build -t azurewebscraper.azurecr.io/imdb-scraper:latest .
        docker push azurewebscraper.azurecr.io/imdb-scraper:latest

    - name: Delete existing container (optional)
      continue-on-error: true
      run: |
        az container delete \
          --resource-group demo \
          --name democontainer \
          --yes

    - name: Deploy to Azure Container Instance
      run: |
        az container create \
          --resource-group demo \
          --name democontainer \
          --image azurewebscraper.azurecr.io/imdb-scraper:latest \
          --cpu 1 \
          --memory 1.5 \
          --restart-policy OnFailure \
          --ip-address public \
          --ports 80
